# Ryan Crop, Variables Practice Python

name = ("Ryan Crop")
small_number = ("7")
big_number = ("99")
breakfeast = ("Cinnomin toast crunch")
color = ("Red")
school = ("UCAS")
year = ("2025")
eye_color = ("Blue")
age = ("15")
subject = ("Coding")

print(f"{name}.\n")
print(f"{small_number}.\n")
print(f"{big_number}.\n")
print(f"{breakfeast}.\n")
print(f"{color}.\n")
print(f"{school}.\n")
print(f"{year}.\n")
print(f"{eye_color}.\n")
print(f"{age}.\n")
print(f"{subject}.\n")